### ISSUE TITLE
Content in vertical "pager"is limited to 10 "objects"

### ISSUE THREAD

**Issue by nila2204** [horvathtamasattila/NavigationComposer#1]
Hi, 
It is impossible for me to create more than 10 screens even though I set screenCount to correct number corresponding to number of objects in content. Is there way how to override that and add more objects to that vertical pager? 
Thanks for your answers!

**Comment by horvathtamasattila** [comment]
Hey, sorry for the late reply. I think your issue is related to the global SwiftUI limitation, that a view can only handle 10 child views. Check [this](https://stackoverflow.com/questions/58397964/are-there-maximum-limits-to-vstack) for more info. I hope I could help you.
